# Generated by Django 4.2.7 on 2026-02-21 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prospect_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('point_of_contact', models.CharField(blank=True, help_text='Person or channel they came from', max_length=200)),
                ('prospect_response', models.TextField(blank=True, help_text='Their response or feedback')),
                ('remarks', models.TextField(blank=True, help_text='Internal notes')),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('proposal', 'Proposal Sent'), ('negotiation', 'Negotiation'), ('won', 'Won'), ('lost', 'Lost')], default='new', max_length=20)),
                ('color_code', models.CharField(blank=True, choices=[('', 'No Color'), ('#28a745', 'Green - Hot Lead'), ('#ffc107', 'Yellow - Warm Lead'), ('#17a2b8', 'Blue - New'), ('#6c757d', 'Gray - Cold'), ('#dc3545', 'Red - Urgent'), ('#e83e8c', 'Pink - Follow Up'), ('#fd7e14', 'Orange - Interested'), ('#20c997', 'Teal - Qualified')], max_length=20)),
                ('source', models.CharField(blank=True, help_text='Lead source e.g. Website, Referral', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
